import React, { useCallback, useEffect, useState } from "react";
import { Clock3, LogIn, LogOut, RefreshCw } from "lucide-react";
import Swal from "sweetalert2";
import { toast } from "react-toastify";
import { checkAttendanceStatusApi, checkInApi, checkOutApi, getOwnAttendanceHistoryApi } from "../../services/adminService";
import { formatDateTime } from "../../utils/orderDisplay";
import "./Attendance.scss";

const formatMinutes=(minutes)=>minutes===null||minutes===undefined?"Open shift":`${Math.floor(minutes/60)}h ${minutes%60}m`;
const Attendance=()=>{const[status,setStatus]=useState({isClockedIn:false,latestRecord:null});const[history,setHistory]=useState({logs:[],page:1,totalPages:1});const[filters,setFilters]=useState({dateFrom:"",dateTo:""});const[page,setPage]=useState(1);const[elapsed,setElapsed]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
const load=useCallback(async()=>{setLoading(true);setError("");try{const[current,logs]=await Promise.all([checkAttendanceStatusApi(),getOwnAttendanceHistoryApi({page,limit:15,...filters})]);if(current?.EC!==0)throw new Error(current?.EM);if(logs?.EC!==0)throw new Error(logs?.EM);setStatus(current.DT);setHistory(logs.DT)}catch(e){setError(e?.EM||e?.message||"Attendance could not be loaded.")}finally{setLoading(false)}},[filters,page]);useEffect(()=>{load()},[load]);useEffect(()=>{if(!status.isClockedIn||!status.latestRecord)return undefined;const update=()=>setElapsed(Math.max(0,Math.floor((Date.now()-new Date(status.latestRecord.check_in_time).getTime())/1000)));update();const timer=setInterval(update,1000);return()=>clearInterval(timer)},[status]);
const act=async(kind)=>{if(kind==="out"){const confirm=await Swal.fire({title:"End this shift?",icon:"warning",showCancelButton:true,confirmButtonText:"Check out"});if(!confirm.isConfirmed)return}setBusy(true);try{const response=kind==="in"?await checkInApi():await checkOutApi();if(response?.EC!==0)throw new Error(response?.EM);toast.success(kind==="in"?"Checked in.":"Checked out.");await load()}catch(e){toast.error(e?.EM||e?.message||"Attendance action failed.")}finally{setBusy(false)}};const elapsedLabel=`${String(Math.floor(elapsed/3600)).padStart(2,"0")}:${String(Math.floor(elapsed%3600/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`;
return <main className="staff-attendance"><header><div><span>Staff self-service</span><h1>Attendance</h1><p>Your shift history is private to your account.</p></div><button onClick={load}><RefreshCw size={16}/>Refresh</button></header>{loading?<div className="attendance-state">Loading attendance...</div>:error?<div className="attendance-state error">{error}</div>:<><section className={`shift-card ${status.isClockedIn?"open":"closed"}`}><Clock3/><div><span>Current state</span><h2>{status.isClockedIn?"Clocked in":"Clocked out"}</h2>{status.latestRecord&&<p>{status.isClockedIn?`Started ${formatDateTime(status.latestRecord.check_in_time)}`:`Last shift ended ${formatDateTime(status.latestRecord.check_out_time)}`}</p>}</div>{status.isClockedIn?<div className="shift-action"><strong>{elapsedLabel}</strong><button disabled={busy} onClick={()=>act("out")}><LogOut size={17}/>Check out</button></div>:<div className="shift-action"><button disabled={busy} onClick={()=>act("in")}><LogIn size={17}/>Check in</button></div>}</section><section className="attendance-history"><div className="attendance-history-heading"><div><h2>Your shift history</h2><p>Shifts belong to the date of check-in; overnight shifts are not split.</p></div><div><input type="date" value={filters.dateFrom} onChange={(e)=>{setPage(1);setFilters((v)=>({...v,dateFrom:e.target.value}))}}/><input type="date" value={filters.dateTo} onChange={(e)=>{setPage(1);setFilters((v)=>({...v,dateTo:e.target.value}))}}/></div></div>{history.logs.length===0?<div className="attendance-state">No shifts in this date range.</div>:<div className="attendance-log-list">{history.logs.map((log)=><article key={log.id}><div><strong>{new Date(log.check_in_time).toLocaleDateString()}</strong><small>{log.is_open?"Open":"Completed"}</small></div><span>{formatDateTime(log.check_in_time)}</span><span>{log.check_out_time?formatDateTime(log.check_out_time):"—"}</span><strong className={log.has_invalid_duration?"invalid":""}>{log.has_invalid_duration?"Invalid duration":formatMinutes(log.worked_minutes)}</strong></article>)}</div>}<footer><button disabled={page<=1} onClick={()=>setPage((v)=>v-1)}>Previous</button><span>Page {history.page||page} of {Math.max(history.totalPages||1,1)}</span><button disabled={page>=(history.totalPages||1)} onClick={()=>setPage((v)=>v+1)}>Next</button></footer></section></>}</main>};export default Attendance;
